### Dictionary keys 0--ii ###

L='length'
b='width'
b_mm='width mm'
D='depth'
D_mm='depth mm'
d='effective depth'
d_mm='effective depth mm'
spanEnds='span end positions'
fy='steel grade'
fck='concrete grade'
stirDia='stirrup diameter mm'
Asv='stirrup area mm2'
fems='fixed end moments'
l='left'
r='right'
reacs='reactions'
pLs='point loads'
mag='magnitude'
pos='position'
udls='UDLs'
strPos='start position'
endPos='end position'
eqPL='equivalent point load'
df='distribution factor'
I='inertia'
fbd='FBD'
endMoms='end moments'
momVals='moment values'
sfVals='shear force values'
Xumax='Xumax'
Ru='Ru'
Mulim='Mulim'
Ast='area of steel under tension (at every 1/10 of span)'
Asc='area of steel under compression (at every 1/10 of span)'
Sv='stirrup spacing (at every 1/10 of span)'

### Dictionary keys 0--ii END ###